/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab9;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author mitchdunc
 */
public class StudentRecordDatabaseGUI extends javax.swing.JFrame {
    ArrayList<Student> data = new ArrayList<>();
    AuthServer authServer = new AuthServer();
    StudentServer studentServer = new StudentServer();
    
    int currentType = 0;
    //0 = none selected
        //1 = undergrad
        //2 = grad
        //3 = non-degree
    
    /**
     * Creates new form StudentRecordDatabaseGUI
     */
    public StudentRecordDatabaseGUI() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        exitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        executeButton = new javax.swing.JButton();
        loginButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        firstNameText = new javax.swing.JTextField();
        lastNameText = new javax.swing.JTextField();
        middleInitText = new javax.swing.JTextField();
        stateText = new javax.swing.JTextField();
        addressText = new javax.swing.JTextField();
        collegeText = new javax.swing.JTextField();
        majorComboBox = new javax.swing.JComboBox();
        collegeComboBox = new javax.swing.JComboBox();
        zipComboBox = new javax.swing.JComboBox();
        countryComboBox = new javax.swing.JComboBox();
        thesisRadioButton = new javax.swing.JRadioButton();
        nonThesisRadioButton = new javax.swing.JRadioButton();
        phdRadioButton = new javax.swing.JRadioButton();
        msRadioButton = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        puidText = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenu();
        underGradMenuItem = new javax.swing.JMenuItem();
        gradMenuItem = new javax.swing.JMenuItem();
        nonDegreeMenuItem = new javax.swing.JMenuItem();
        loginMenuItem = new javax.swing.JMenuItem();
        menuSave = new javax.swing.JMenuItem();
        menuClear = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuQueryEnter = new javax.swing.JMenuItem();
        MenuQueryExecute = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuHelpAbout = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        exitButton.setText("Exit");
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(exitButton);

        clearButton.setText("Clear");
        clearButton.setFocusable(false);
        clearButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        clearButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(clearButton);

        saveButton.setText("Save");
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);

        executeButton.setText("Execute");
        executeButton.setFocusable(false);
        executeButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        executeButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        executeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(executeButton);

        loginButton.setText("Login");
        loginButton.setFocusable(false);
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(loginButton);

        jLabel1.setText("First Name:");

        jLabel2.setText("Middle Initial:");

        jLabel3.setText("Last Name:");

        jLabel4.setText("Address:");

        jLabel5.setText("State:");

        jLabel6.setText("Zip Code:");

        jLabel7.setText("Country");

        jLabel8.setText("Major");

        jLabel9.setText("College");

        jLabel10.setText("Thesis or Non-Thesis");

        jLabel11.setText("MS or PHD");

        firstNameText.setEnabled(false);
        firstNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameTextActionPerformed(evt);
            }
        });

        lastNameText.setEnabled(false);
        lastNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameTextActionPerformed(evt);
            }
        });

        middleInitText.setEnabled(false);
        middleInitText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                middleInitTextActionPerformed(evt);
            }
        });

        stateText.setEnabled(false);
        stateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateTextActionPerformed(evt);
            }
        });

        addressText.setEnabled(false);
        addressText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTextActionPerformed(evt);
            }
        });

        collegeText.setEnabled(false);
        collegeText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeTextActionPerformed(evt);
            }
        });

        majorComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CIT", "Physics", "Math", "Plant Science", "7-Year Plan" }));
        majorComboBox.setSelectedIndex(-1);
        majorComboBox.setEnabled(false);
        majorComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                majorComboBoxActionPerformed(evt);
            }
        });

        collegeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "School of Technology", "School of Engineering", "School of Liberal Arts" }));
        collegeComboBox.setSelectedIndex(-1);
        collegeComboBox.setToolTipText("");
        collegeComboBox.setEnabled(false);
        collegeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collegeComboBoxActionPerformed(evt);
            }
        });

        zipComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "46062", "46063", "46064", "47906", "47907" }));
        zipComboBox.setSelectedIndex(-1);
        zipComboBox.setEnabled(false);
        zipComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zipComboBoxActionPerformed(evt);
            }
        });

        countryComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "United States of America", "Peru", "Chile", "France", "Germany", "UK" }));
        countryComboBox.setSelectedIndex(-1);
        countryComboBox.setEnabled(false);
        countryComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                countryComboBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(thesisRadioButton);
        thesisRadioButton.setText("Thesis");
        thesisRadioButton.setEnabled(false);
        thesisRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thesisRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nonThesisRadioButton);
        nonThesisRadioButton.setText("Non-Thesis");
        nonThesisRadioButton.setEnabled(false);

        buttonGroup2.add(phdRadioButton);
        phdRadioButton.setText("PHD");
        phdRadioButton.setEnabled(false);
        phdRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phdRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup2.add(msRadioButton);
        msRadioButton.setText("MS");
        msRadioButton.setEnabled(false);
        msRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                msRadioButtonActionPerformed(evt);
            }
        });

        jLabel12.setText("PUID:");

        puidText.setEnabled(false);
        puidText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puidTextActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        newMenuItem.setText("New");
        newMenuItem.setEnabled(false);

        underGradMenuItem.setText("UnderGrad");
        underGradMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                underGradMenuItemActionPerformed(evt);
            }
        });
        newMenuItem.add(underGradMenuItem);

        gradMenuItem.setText("Graduate");
        gradMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradMenuItemActionPerformed(evt);
            }
        });
        newMenuItem.add(gradMenuItem);

        nonDegreeMenuItem.setText("Non-Degree");
        nonDegreeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nonDegreeMenuItemActionPerformed(evt);
            }
        });
        newMenuItem.add(nonDegreeMenuItem);

        jMenu1.add(newMenuItem);

        loginMenuItem.setText("Login");
        jMenu1.add(loginMenuItem);

        menuSave.setText("Save");
        menuSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSaveActionPerformed(evt);
            }
        });
        jMenu1.add(menuSave);

        menuClear.setText("Clear");
        menuClear.setToolTipText("");
        menuClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClearActionPerformed(evt);
            }
        });
        jMenu1.add(menuClear);

        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Query");

        menuQueryEnter.setText("Enter");
        menuQueryEnter.setToolTipText("");
        menuQueryEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuQueryEnterActionPerformed(evt);
            }
        });
        jMenu2.add(menuQueryEnter);

        MenuQueryExecute.setText("Execute");
        MenuQueryExecute.setToolTipText("");
        MenuQueryExecute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuQueryExecuteActionPerformed(evt);
            }
        });
        jMenu2.add(MenuQueryExecute);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Help");

        MenuHelpAbout.setText("About");
        MenuHelpAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuHelpAboutActionPerformed(evt);
            }
        });
        jMenu4.add(MenuHelpAbout);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(26, 26, 26)
                                        .addComponent(thesisRadioButton))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(msRadioButton)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(phdRadioButton)
                                    .addComponent(nonThesisRadioButton)))
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel12))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(puidText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(zipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(majorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(middleInitText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(collegeText, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(collegeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 233, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(firstNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(middleInitText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lastNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(puidText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(stateText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(zipComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(countryComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(majorComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(collegeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(collegeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(thesisRadioButton)
                    .addComponent(nonThesisRadioButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(phdRadioButton)
                    .addComponent(msRadioButton))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Do you want to quit?", "Quit", JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        // TODO add your handling code here:
        firstNameText.setText(null);
        firstNameText.setEnabled(false);
        
        middleInitText.setText(null);
        middleInitText.setEnabled(false);
        
        lastNameText.setText(null);
        lastNameText.setEnabled(false);
        
        puidText.setText(null);
        puidText.setEnabled(false);
        
        addressText.setText(null);
        addressText.setEnabled(false);
        
        stateText.setText(null);
        stateText.setEnabled(false);
        
        zipComboBox.setSelectedIndex(-1);
        zipComboBox.setEnabled(false);
        
        countryComboBox.setSelectedIndex(-1);
        countryComboBox.setEnabled(false);
        
        majorComboBox.setSelectedIndex(-1);
        majorComboBox.setEnabled(false);
        
        collegeComboBox.setSelectedIndex(-1);
        collegeComboBox.setEnabled(false);
        
        collegeText.setText(null);
        collegeText.setEnabled(false);
        
        buttonGroup1.clearSelection();
        thesisRadioButton.setSelected(false);
        thesisRadioButton.setEnabled(false);
        
        nonThesisRadioButton.setSelected(false);
        nonThesisRadioButton.setEnabled(false);
        
        buttonGroup2.clearSelection();
        msRadioButton.setSelected(false);
        msRadioButton.setEnabled(false);
        
        phdRadioButton.setSelected(false);
        phdRadioButton.setEnabled(false);
        
        currentType = 0;
    }//GEN-LAST:event_clearButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
            //0 = none selected
        //1 = undergrad
        //2 = grad
        //3 = non-degree
        
        

        switch (currentType){
            case 1:// undergrad
                Student underGrad = new UnderGrad(firstNameText.getText(), middleInitText.getText(), lastNameText.getText(), puidText.getText(), addressText.getText(), stateText.getText(),
                zipComboBox.getSelectedIndex(), countryComboBox.getSelectedIndex(), majorComboBox.getSelectedIndex(), collegeComboBox.getSelectedIndex());
                data.add(underGrad);
                JOptionPane.showMessageDialog(null, "The UnderGrad Student Was saved!", "Saved!", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 2: //grad
                Student grad = new Graduate(firstNameText.getText(), middleInitText.getText(), lastNameText.getText(), puidText.getText(), addressText.getText(),
                stateText.getText(), zipComboBox.getSelectedIndex(), countryComboBox.getSelectedIndex(), majorComboBox.getSelectedIndex(), collegeComboBox.getSelectedIndex(),
                thesisRadioButton.isSelected(), nonThesisRadioButton.isSelected(), phdRadioButton.isSelected(), msRadioButton.isSelected());
                data.add(grad);
                JOptionPane.showMessageDialog(null, "The Grad Student Was saved!", "Saved!", JOptionPane.INFORMATION_MESSAGE);
                break;
            case 3: //non-degree
                Student nonDegree = new NonDegree(firstNameText.getText(), middleInitText.getText(), lastNameText.getText(), puidText.getText(), addressText.getText(),
                stateText.getText(), zipComboBox.getSelectedIndex(), countryComboBox.getSelectedIndex(), collegeText.getText());
                data.add(nonDegree);
                JOptionPane.showMessageDialog(null, "The Non-Degree Student Was saved!", "Saved!", JOptionPane.INFORMATION_MESSAGE);
                break;
            default: 
                JOptionPane.showMessageDialog(null, "Please select a new student first.", "Error!", JOptionPane.INFORMATION_MESSAGE);
                break;
                
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void executeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeButtonActionPerformed
        // TODO add your handling code here:
        this.MenuQueryExecute.doClick();
    }//GEN-LAST:event_executeButtonActionPerformed

    private void firstNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameTextActionPerformed

    private void lastNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameTextActionPerformed

    private void middleInitTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_middleInitTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_middleInitTextActionPerformed

    private void stateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateTextActionPerformed

    private void addressTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTextActionPerformed

    private void collegeTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeTextActionPerformed

    private void majorComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_majorComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_majorComboBoxActionPerformed

    private void collegeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collegeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collegeComboBoxActionPerformed

    private void zipComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zipComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_zipComboBoxActionPerformed

    private void countryComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_countryComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_countryComboBoxActionPerformed

    private void thesisRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thesisRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_thesisRadioButtonActionPerformed

    private void phdRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phdRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phdRadioButtonActionPerformed

    private void msRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_msRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_msRadioButtonActionPerformed

    private void underGradMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_underGradMenuItemActionPerformed
        // TODO add your handling code here:
        firstNameText.setText(null);
        firstNameText.setEnabled(true);
        
        middleInitText.setText(null);
        middleInitText.setEnabled(true);
        
        lastNameText.setText(null);
        lastNameText.setEnabled(true);
        
        puidText.setText(null);
        puidText.setEnabled(true);
        
        addressText.setText(null);
        addressText.setEnabled(true);
        
        stateText.setText(null);
        stateText.setEnabled(true);
        
        zipComboBox.setSelectedIndex(-1);
        zipComboBox.setEnabled(true);
        
        countryComboBox.setSelectedIndex(-1);
        countryComboBox.setEnabled(true);
        
        majorComboBox.setSelectedIndex(-1);
        majorComboBox.setEnabled(true);
        
        collegeComboBox.setSelectedIndex(-1);
        collegeComboBox.setEnabled(true);
        
        collegeText.setText(null);
        collegeText.setEnabled(false);
        
        thesisRadioButton.setSelected(false);
        thesisRadioButton.setEnabled(false);
        
        nonThesisRadioButton.setSelected(false);
        nonThesisRadioButton.setEnabled(false);
        
        msRadioButton.setSelected(false);
        msRadioButton.setEnabled(false);
        
        phdRadioButton.setSelected(false);
        phdRadioButton.setEnabled(false);
        
        //Select grad type
        currentType = 1;
        
        
    }//GEN-LAST:event_underGradMenuItemActionPerformed

    private void gradMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradMenuItemActionPerformed
        // TODO add your handling code here:
                firstNameText.setText(null);
        firstNameText.setEnabled(true);
        
        middleInitText.setText(null);
        middleInitText.setEnabled(true);
        
        lastNameText.setText(null);
        lastNameText.setEnabled(true);
        
        puidText.setText(null);
        puidText.setEnabled(true);
        
        addressText.setText(null);
        addressText.setEnabled(true);
        
        stateText.setText(null);
        stateText.setEnabled(true);
        
        zipComboBox.setSelectedIndex(-1);
        zipComboBox.setEnabled(true);
        
        countryComboBox.setSelectedIndex(-1);
        countryComboBox.setEnabled(true);
        
        majorComboBox.setSelectedIndex(-1);
        majorComboBox.setEnabled(true);
        
        collegeComboBox.setSelectedIndex(-1);
        collegeComboBox.setEnabled(true);
        
        collegeText.setText(null);
        collegeText.setEnabled(false);
        
        thesisRadioButton.setSelected(false);
        thesisRadioButton.setEnabled(true);
        
        nonThesisRadioButton.setSelected(false);
        nonThesisRadioButton.setEnabled(true);
        
        msRadioButton.setSelected(false);
        msRadioButton.setEnabled(true);
        
        phdRadioButton.setSelected(false);
        phdRadioButton.setEnabled(true);
        
        currentType = 2;
        
    }//GEN-LAST:event_gradMenuItemActionPerformed

    private void nonDegreeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nonDegreeMenuItemActionPerformed
        // TODO add your handling code here:
                firstNameText.setText(null);
        firstNameText.setEnabled(true);
        
        middleInitText.setText(null);
        middleInitText.setEnabled(true);
        
        lastNameText.setText(null);
        lastNameText.setEnabled(true);
        
        puidText.setText(null);
        puidText.setEnabled(true);
        
        addressText.setText(null);
        addressText.setEnabled(true);
        
        stateText.setText(null);
        stateText.setEnabled(true);
        
        zipComboBox.setSelectedIndex(-1);
        zipComboBox.setEnabled(true);
        
        countryComboBox.setSelectedIndex(-1);
        countryComboBox.setEnabled(true);
        
        majorComboBox.setSelectedIndex(-1);
        majorComboBox.setEnabled(false);
        
        collegeComboBox.setSelectedIndex(-1);
        collegeComboBox.setEnabled(false);
        
        collegeText.setText(null);
        collegeText.setEnabled(true);
        
        buttonGroup1.clearSelection();
        thesisRadioButton.setEnabled(false);
        nonThesisRadioButton.setEnabled(false);
        
        buttonGroup2.clearSelection();
        msRadioButton.setEnabled(false);
        phdRadioButton.setEnabled(false);
        
        currentType = 3; 
        
    }//GEN-LAST:event_nonDegreeMenuItemActionPerformed

    private void puidTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puidTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puidTextActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        int exit = JOptionPane.showConfirmDialog(null, "Do you want to quit?", "Quit", JOptionPane.YES_NO_OPTION);
        if(exit == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClearActionPerformed
        // TODO add your handling code here:
        firstNameText.setText(null);
        firstNameText.setEnabled(false);
        
        middleInitText.setText(null);
        middleInitText.setEnabled(false);
        
        lastNameText.setText(null);
        lastNameText.setEnabled(false);
        
        puidText.setText(null);
        puidText.setEnabled(false);
        
        addressText.setText(null);
        addressText.setEnabled(false);
        
        stateText.setText(null);
        stateText.setEnabled(false);
        
        zipComboBox.setSelectedIndex(-1);
        zipComboBox.setEnabled(false);
        
        countryComboBox.setSelectedIndex(-1);
        countryComboBox.setEnabled(false);
        
        majorComboBox.setSelectedIndex(-1);
        majorComboBox.setEnabled(false);
        
        collegeComboBox.setSelectedIndex(-1);
        collegeComboBox.setEnabled(false);
        
        collegeText.setText(null);
        collegeText.setEnabled(false);
        
        buttonGroup1.clearSelection();
        thesisRadioButton.setSelected(false);
        thesisRadioButton.setEnabled(false);
        
        nonThesisRadioButton.setSelected(false);
        nonThesisRadioButton.setEnabled(false);
        
        buttonGroup2.clearSelection();
        msRadioButton.setSelected(false);
        msRadioButton.setEnabled(false);
        
        phdRadioButton.setSelected(false);
        phdRadioButton.setEnabled(false);
        
        currentType = 0;
    }//GEN-LAST:event_menuClearActionPerformed

    private void MenuHelpAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuHelpAboutActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Dev Name: Mitchdunc \n Dev Email: mitchdunc@gmail.com", "About the program", JOptionPane.INFORMATION_MESSAGE);
     
    }//GEN-LAST:event_MenuHelpAboutActionPerformed

    private void menuSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSaveActionPerformed
        // TODO add your handling code here:
        this.saveButton.doClick();
    }//GEN-LAST:event_menuSaveActionPerformed

    private void menuQueryEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQueryEnterActionPerformed
        // TODO add your handling code here:
        
        firstNameText.setEnabled(false);
        middleInitText.setEnabled(false);
        lastNameText.setEnabled(false);
        puidText.setEnabled(true);
        addressText.setEnabled(false);
        stateText.setEnabled(false);
        zipComboBox.setEnabled(false);
        countryComboBox.setEnabled(false);
        majorComboBox.setEnabled(false);
        collegeComboBox.setEnabled(false);
        collegeText.setEnabled(false);
        thesisRadioButton.setEnabled(false);
        nonThesisRadioButton.setEnabled(false);
        phdRadioButton.setEnabled(false);
        msRadioButton.setEnabled(false);
    }//GEN-LAST:event_menuQueryEnterActionPerformed

    private void MenuQueryExecuteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuQueryExecuteActionPerformed
        // TODO add your handling code here:
        String puid = puidText.getText();
        boolean foundStudent = false;
        
        for(Student person: data){
            if(person.getPuid().equals(puid)){
                foundStudent = true;
                firstNameText.setEnabled(true);
                firstNameText.setText(person.getFirstName());
                middleInitText.setEnabled(true);
                middleInitText.setText(person.getMiddleInit());
                lastNameText.setEnabled(true);
                lastNameText.setText(person.getLastName());
                puidText.setEnabled(true);
                puidText.setText(person.getPuid());
                addressText.setEnabled(true);
                addressText.setText(person.getAddress());
                stateText.setEnabled(true);
                stateText.setText(person.getState());
                zipComboBox.setEnabled(true);
                zipComboBox.setSelectedIndex(person.getZipCode());
                countryComboBox.setEnabled(true);
                countryComboBox.setSelectedIndex(person.getCountry());
                
                if(person instanceof UnderGrad){
                    UnderGrad newUnderGrad = (UnderGrad)person;
                    majorComboBox.setEnabled(true);
                    majorComboBox.setSelectedIndex(newUnderGrad.getMajor());
                    collegeComboBox.setEnabled(true);
                    collegeComboBox.setSelectedIndex(newUnderGrad.getSchool());
                    currentType = 1;
                
                }
                else if(person instanceof Graduate){
                    Graduate newGraduate = (Graduate)person;
                    
                    majorComboBox.setEnabled(true);
                    majorComboBox.setSelectedIndex(newGraduate.getMajor());
                    collegeComboBox.setEnabled(true);
                    collegeComboBox.setSelectedIndex(newGraduate.getSchool());
                    thesisRadioButton.setEnabled(true);
                    thesisRadioButton.setSelected(newGraduate.isThesis());
                    nonThesisRadioButton.setEnabled(true);
                    nonThesisRadioButton.setSelected(newGraduate.isNonThesis());
                    phdRadioButton.setEnabled(true);
                    phdRadioButton.setSelected(newGraduate.isPhd());
                    msRadioButton.setEnabled(true);
                    msRadioButton.setSelected(newGraduate.isMs());
                    currentType = 2;
                    
                    
                }
                else if(person instanceof NonDegree){
                    NonDegree newNonDegree = (NonDegree)person;
                    collegeText.setEnabled(true);
                    collegeText.setText(newNonDegree.getCollege());
                    currentType = 3;
                }
                
            }
        }
        
        if(!foundStudent){
            JOptionPane.showMessageDialog(null, "No Students were found", "No Results Found", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_MenuQueryExecuteActionPerformed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        // TODO add your handling code here:
        loginAction();
    }//GEN-LAST:event_loginButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentRecordDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentRecordDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentRecordDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentRecordDatabaseGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentRecordDatabaseGUI().setVisible(true);
            }
        });
    }
    
    public void loginAction(){
        
        Login loginGUI = new Login();
        loginGUI.setVisible(true);
        authServer.authUser();
//        while (loginGUI.isActive()) {
//            authServer.acceptClient();
//            authServer.acceptString();
//            if(authServer.authUser()){
//                newMenuItem.setEnabled(true);
//                loginGUI.setVisible(false);
//            }
//            else{
//                JOptionPane.showMessageDialog(null, "The username or password was incorrect.");
//            }
//        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuHelpAbout;
    private javax.swing.JMenuItem MenuQueryExecute;
    private javax.swing.JTextField addressText;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox collegeComboBox;
    private javax.swing.JTextField collegeText;
    private javax.swing.JComboBox countryComboBox;
    private javax.swing.JButton executeButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JTextField firstNameText;
    private javax.swing.JMenuItem gradMenuItem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField lastNameText;
    private javax.swing.JButton loginButton;
    private javax.swing.JMenuItem loginMenuItem;
    private javax.swing.JComboBox majorComboBox;
    private javax.swing.JMenuItem menuClear;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuQueryEnter;
    private javax.swing.JMenuItem menuSave;
    private javax.swing.JTextField middleInitText;
    private javax.swing.JRadioButton msRadioButton;
    private javax.swing.JMenu newMenuItem;
    private javax.swing.JMenuItem nonDegreeMenuItem;
    private javax.swing.JRadioButton nonThesisRadioButton;
    private javax.swing.JRadioButton phdRadioButton;
    private javax.swing.JTextField puidText;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField stateText;
    private javax.swing.JRadioButton thesisRadioButton;
    private javax.swing.JMenuItem underGradMenuItem;
    private javax.swing.JComboBox zipComboBox;
    // End of variables declaration//GEN-END:variables
}
